#!/usr/bin/env bash

dissertation_parent_dir="$HOME/media/usb/dissertations/"
parent_dir_char_length=$(echo "$dissertation_parent_dir" | wc -c)
dissertation=$(find ${dissertation_parent_dir} -type f | cut -c $parent_dir_char_length-)
selected_dissertation=$(echo "$dissertation" | rofi -dmenu -i)
printf "\n \n"
if [ -n "$selected_dissertation" ]; then
  zathura "$dissertation_parent_dir$selected_dissertation"
fi
