#!/usr/bin/env bash

# scripts_dir="$HOME/.scripts/"
# opacity_scriptname="alacritty_opacity.sh"
# source $scripts_dir$opacity_scriptname
# echo $opacity
# incremented_opacity=$(($opacity + 5))
# echo $incremented_opacity

## If alacritty.yml does not exist, raise an alert
[[ ! -f ~/.config/alacritty/alacritty.yml ]] && \
    notify-send "alacritty.yml does not exist" && exit 0

## Fetch background_opacity from alacritty.yml
opacity=$(grep Alacritty ~/.config/picom.conf | grep -o -E "[0-9]+")

max_opacity=100
new_opacity=$(($opacity + 2))


if [ "$new_opacity" -gt "$max_opacity" ]; then
    new_opacity=$max_opacity
fi



## Replace opacity value in alacritty.yml
sed -i -- "s/\"$opacity:class_g = 'Alacritty'\"/\"$new_opacity:class_g = 'Alacritty'\"/" \
    ~/.config/picom.conf
