#!/usr/bin/env bash

#JAR="$HOME/.local/share/lsp/jdtls-server/plugins/org.eclipse.equinox.launcher_*.jar"
#GRADLE_HOME='$HOME/.sdkman/candidates/gradle/current/bin/gradle' 

# java \
#   -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044 \
#   -javaagent:$HOME/.local/jars/lombok.jar \
#   -Xbootclasspath/a:$HOME/.local/jars/lombok.jar \
#   -Declipse.application=org.eclipse.jdt.ls.core.id1 \
#   -Dosgi.bundles.defaultStartLevel=4 \
#   -Declipse.product=org.eclipse.jdt.ls.core.product \
#   -Dlog.protocol=true \
#   -Dlog.level=ALL \
#   -Xms1g \
#   -Xmx2G \
#   -jar $(echo "$JAR") \
#   -configuration "$HOME/.local/share/lsp/jdtls-server/config_linux" \
#   -data "$1" \
#   --add-modules=ALL-SYSTEM \
#   --add-opens java.base/java.util=ALL-UNNAMED \
#   --add-opens java.base/java.lang=ALL-UNNAMED
	#-configuration /usr/share/java/jdtls/config_linux \


java \
	-Declipse.application=org.eclipse.jdt.ls.core.id1 \
	-Dosgi.bundles.defaultStartLevel=4 \
	-Declipse.product=org.eclipse.jdt.ls.core.product \
	-Dlog.level=ALL \
	-noverify \
	-Xmx1G \
	--add-modules=ALL-SYSTEM \
	--add-opens java.base/java.util=ALL-UNNAMED \
	--add-opens java.base/java.lang=ALL-UNNAMED \
	-jar /usr/share/java/jdtls/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar \
	-configuration ~/jdtls/config_linux \
	-data ~/work/navy/JSAPPHIRE
