#!/usr/bin/env python3

import argparse
import os
import re
import random
import sys

# create parser
parser = argparse.ArgumentParser()


# add arguments to the parser
parser.add_argument("--tname", nargs=1, help="Theme name (string wo quotes)")
parser.add_argument("--dmode", nargs=1, help="Dark Mode (True/False)")

# parse the arguments
args = parser.parse_args()

if(args.tname != None):
    given_tname = args.tname[0]
else:
    given_tname = ""

if(args.dmode != None):
    given_dmode = args.dmode[0]
else:
    given_dmode = ""

# given_tname = ""
# given_dmode = ""

# Helper funs (only used once...)
def find_color_bounds(lst, bstring, estring):
    return [i for i, x in enumerate(lst) if x==bstring or x==estring]

colors_dir = "~/git_repos/base16-qutebrowser/themes/default/"
colors_fns = os.listdir(colors_dir)

rindex = random.choice(range(len(colors_fns)))

# read in alacritty theme
qtheme_fp = "~/.config/qutebrowser/config.py"
qtheme_fs = open(qtheme_fp, 'r')
qtheme_con = qtheme_fs.read()
qtheme_conlist = qtheme_con.split('\n')
qtheme_fs.close()

# Define bounding strings
beg_str = '# QUTEBROWSER_COLOR_THEME_BEGIN'
end_str = '# QUTEBROWSER_COLOR_THEME_END'

bounds = find_color_bounds(qtheme_conlist, beg_str, end_str)
bbound = bounds[0]
bound_width = bounds[1] - bounds[0]

for i in range(bound_width-1):
    del qtheme_conlist[bbound+1]

if(given_tname == ''):
    ctheme_fp = os.path.join(colors_dir, colors_fns[rindex])
else:
    inlist = any([given_tname == x for x in colors_fns])
    # add a check if given_tname in list
    if inlist:
        ctheme_fp = os.path.join(colors_dir, given_tname)
    else:
        print(f"Error: {given_tname} not in base16-themes")
        sys.exit()
ctheme_fs = open(ctheme_fp, 'r')
ctheme_con = ctheme_fs.read()
ctheme_conlist = ctheme_con.split('\n')
ctheme_fs.close()

for i in range(len(ctheme_conlist)):
    qtheme_conlist.insert(bbound + 1+ i, ctheme_conlist[i])


matching_dmode_list = [x.find("c.colors.webpage.darkmode.enabled") for x in qtheme_conlist]
dmode_lnum = [index for index,value in enumerate(matching_dmode_list) if value != -1]
dmode_lnum = dmode_lnum[0]

if(given_dmode == "True"):
    qtheme_conlist[dmode_lnum] = "c.colors.webpage.darkmode.enabled = True"
if(given_dmode == "False"):
    qtheme_conlist[dmode_lnum] = "c.colors.webpage.darkmode.enabled = False"

new_qtheme_con = '\n'.join(qtheme_conlist)

qtheme_fs = open(qtheme_fp, 'w')
qtheme_fs.write(new_qtheme_con)
