#!/bin/bash

# grab the purest color definition file
input="~/.cache/wal/colors"
i=0
content=""
while IFS= read -r line
do

    # generate the color list for my style config
    if [ $i -eq 0 ]; then 
        content="${content}  background:${line}00;"
        content="${content}  color$i:${line};"
    else 
        content="${content}  color$i:${line};"
    fi
    echo $content

    ((i++))

done < "$input"

# # copied a template config to the actual config location
# cp ~/.config/rofi/colors-rofi-template.rasi ~/.config/i3/rofi.rasi
